Colors:
    DeathColor: "Red"
    LocationColor: "Yellow"

Icons:
    DeathIconURL: "https://i.imgur.com/RwNhu8v.png"
    LocationIconURL: "https://i.imgur.com/AlIq6xx.png"

Messages:
    LocationMessage: "true"
    AcidMessage: "true"
    AnimalMessage: "true"
    ArenaMessage: "true"
    BleedingMessage: "true"
    BonesMessage: "true"
    BoulderMessage: "true"
    BreathMessage: "true"
    BurnerMessage: "true"
    BurningMessage: "true"
    ChargeMessage: "true"
    FoodMessage: "true"
    FreezingMessage: "true"
    GrenadeMessage: "true"
    GunMessage: "true"
    InfectionMessage: "true"
    KillMessage: "true"
    LandmineMessage: "true"
    MeleeMessage: "true"
    MissileMessage: "true"
    PunchMessage: "true"
    RoadkillMessage: "true"
    SentryMessage: "true"
    ShredMessage: "true"
    SparkMessage: "true"
    SpitMessage: "true"
    SplashMessage: "true"
    SuicideMessage: "true"
    VehicleMessage: "true"
    WaterMessage: "true"
    ZombieMessage: "true"